language: objective-c
cache:
osx_image: xcode8.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

before_install:
- brew update
- brew bundle
- bundle
- carthage update

script:
- fastlane all_tests

after_success:
- bash <(curl -s https://codecov.io/bash)
