language: objective-c
cache: bundler
osx_image: xcode8.3
branches:
  only:
  - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

before_install:
- brew update
- brew bundle

script:
- fastlane all_tests
