language: objective-c
osx_image: xcode8.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=SwiftyJanet.xcodeproj
  - IOS_SCHEME="SwiftyJanet-iOS"
  - IOS_SDK=iphonesimulator10.2
  - OSX_SCHEME="SwiftyJanet-MacOS"
  - OSX_SDK=macosx10.12
  - TVOS_SCHEME="SwiftyJanet-tvOS"
  - TVOS_SDK=appletvsimulator10.2
  matrix:
    - DESTINATION="OS=10.2,name=iPhone 6S Plus"   SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"
    - DESTINATION="arch=x86_64"                   SCHEME="$OSX_SCHEME"     SDK="$OSX_SDK"
    - DESTINATION="OS=10.2,name=Apple TV 1080p"   SCHEME="$TVOS_SCHEME"    SDK="$TVOS_SDK"

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
